linuxkerneltravel/lmp

deployments/sys/collect.go, internal/BPF/bpf.go, internal/BPF/cbuilder.go, internal/BPF/pybuilder.go, routers/r_sys.go
Build BPF generator using the builder pattern
=> Build BPF generator using the builder pattern

makefile
=> fix the filename

api/handle.go
fix /api/handle.go some word
Another error is left to other students to modify
=> fix /api/handle.go some word

test/grafana/lmp-1587558315630.json
解决：lmp/test/grafana/ 下面的文件名好奇怪 #33
=> change the filename

api/handle.go, cmd/main.go, config/config.go
To adapt the program to the personal enviroment
=> Modify the configuration

api/handle.go, deployments/sys/collect.go, internal/BPF/cbuilder.go, internal/BPF/pybuilder.go
Extended Interface : the configuration file
=>  Extended Interface

internal/bpfcode/bpf-py.txt, internal/bpfcode/code.go
python component of additional vfsstat
=> python component of additional vfsstat

cmd/main.go, common/influxdb/influxdb.go
=> fix influxdb

test/influxdb_test/db_modules.py, test/influxdb_test/lmp_influxdb.py, test/influxdb_test/test1.py
写入数据和删除数据包装好了
查找数据变化比较多，还没想好咋弄
=> influxdb连接

api/handle.go, common/influxdb/influxdb.go, common/influxdb/modules.go, common/mysql/mysql.go, go.mod, go.sum, pkg/model/function.go, pkg/model/message.go, static/login.html
boom shakalaka~
User registration function implementation: registration, data validation, data persistence by Mysql.
BTW : The students in charge of front-end work hardly. The page I wrote is too ugly. Please...
=> Data persistence: add Mysql

api/handle.go, cmd/main.go, daemon/bpf-scan.go, internal/BPF/bpf.go, static/file.html
1. Add front-end pages, only file submission
2. The handler function is LoadFiles(), only single file uploads are currently implemented. All files are saved in the /plugins directory
=> Added user upload plugin function

api/handle.go, cmd/main.go
Short Connection Mode. Need to write a timer on the front end.
=> Add functionality: Feedback all plug-in names to the front end

api/handle.go, cmd/main.go, config/config.go
The front-end students are in urgent need of writing the front page.
=> Upload multiple files once

Rebuild/cmd/handler.go, Rebuild/cmd/main.go, Rebuild/common/config/config.go, common/mysql/modules.go
=> Rebuild cli

Rebuild/cmd/handler.go, Rebuild/cmd/main.go, Rebuild/common/http/http.go, Rebuild/makefile
=> rebuild gin

README.md
Fix readme about installing lmp.
=> Fix readme about installing lmp.

plugins/api.py, plugins/config.py, plugins/cpuutilize.py, plugins/irq.py, plugins/lmp_influxdb.py, plugins/memusage.py, plugins/netlatency.py, plugins/picknext.py, plugins/taskswitch.py, plugins/vfsstat.py, plugins/waitingqueuelength.py
TO-DO:
- 环境没有搭建，仍未完成测试
@LinkinPF
=> feat: python read config from yaml

plugins/config.py
=> fix: relative_path

docs/logic_demo/pluginInfo.go
Add two time points to update the database on the basis of @lil-duck 's code
=> chenyu.zhao : add mysql todilist

.github/workflows/ci.yml
**这个PR做了什么:**
- 利用`GitHub Actions` 完成基础的`CI`任务。
- 基于 `ubuntu18.04`。当提交PR到 `master` 时运行`CI`，进行 编译 `lmp` 、运行单元测试。
`CI`步骤如下：
1. 配置 `go` 环境并编译 `lmp`
2. 拉取并运行 `grafana influxdb`
3. 配置`python` 环境
4. 配置`bcc` 环境 
**to-do list:**
=> feat: ci_demo

misc/init.sql
Each performance index has the following fields:
1. id
2. name
3. exec_path
4. instruction
5. state
=> chenyu.zhao: add mysql init SQL file

logic/plugins.go
=> [Chenyu Zhao] : implement Run() method

logic/storage.go
update class PluginStorage and it's method
=> [Chenyu Zhao] : update class PluginStorage and it's method

controllers/collect_handler.go, logic/collect_handler.go
update the controller and logic layer
=> [Chenyu Zhao] : update the controller and logic layer

logic/storage.go
modification of PluginStorage's methods
=> [Chenyu Zhao] : modification of PluginStorage's methods

controllers/collect_handler.go, logic/collect_handler.go
modification of controller and logic layer
=> [Chenyu Zhao] : modification of controller and logic layer

logic/collect_handler.go
=> [Chenyu Zhao] : alter import

logic/collect_handler.go, logic/storage.go
=> [Chenyu Zhao] : alter code

logic/storage.go, models/param.go
Implementation of the CreatePluginStorage method
=> [Chenyu Zhao] : Implementation of the CreatePluginStorage method

logic/plugins.go
=> [Chenyu Zhao] : alter CreatePlugin method

logic/collect_handler.go
=> [Chenyu Zhao] : alter logic layer

logic/storage.go
Implementation of the CollectData method
=> [Chenyu Zhao] : Implementation of the CollectData method

models/param.go
=> [Chenyu Zhao] : fix json bug

static/index.html
1. 将index.html使用elementUI(基于Vue.js)框架进行重写；
2. 采用Ajax的方式，POST采集指标到后端。 
#133
=> 重新实现了index.html

config.yaml, main.go, misc/init.sql
=> [Chenyu Zhao] : add sql file

logic/plugins.go, logic/storage.go
=> [Chenyu Zhao] : alter logic

misc/init.sql
=> [Chenyu Zhao] : modified the sql file

Makefile, config.yaml
Alter makefile and yaml config file.
=> [Chenyu Zhao] : alter makefile and yaml config file

Makefile
=> [Chenyu Zhao] : add db in makefile

logic/error_code.go, logic/plugins.go, logic/storage.go
Add error message in logic layer.
=> [Chenyu Zhao] : Add error message in logic layer.

docs/messageQueue_demo/main.go, docs/messageQueue_demo/mq/MQ.go, docs/messageQueue_demo/mq/client.go, docs/messageQueue_demo/mq/client_test.go
=> [Chenyu Zhao] : Add messageQueue demo

main.go, modules/profile_cluster.go, modules/service.go
=> [Chenyu Zhao]: Add cluster demo.

README.md, docs/增加一个模型.md, modules/profile_cluster.go, modules/service.go
=> [Chenyu Zhao] : Add docs and alter readme

main.go, modules/service.go
=> [Chenyu Zhao] : Add function GetModules()

modules/profile_cluster.go, modules/service.go
Add function registerModules()
=> [Chenyu Zhao] : Add function registerModules()

Makefile, README.md, misc/init.sql
数据库初始化时未创建数据库导致出错，现修改如下：
1. 初始化时建立数据库lmp。
2. make db --》sudo make db
=> Modify MySQL Database init

static/index.html
实现了issues #180 中的第二点：
index.html页面修改为列表形式，列表形式可以展示更多的指标信息（如指标名称、介绍、状态等）。
=> 使用table组件改写了指标下发页面

plugins/io_collector/config/sysfs/sysfs.go, plugins/io_collector/dao/args_dao.go, plugins/io_collector/dao/dict_dao.go, plugins/io_collector/db/db_conn.go, plugins/io_collector/monitor/collect.go, plugins/io_collector/utils/string_utils.go
根据参数抽样数据集设置系统参数，采集不同参数配置、不同负载下的IO性能指标。
因为Mysql数据库和前端入口还没有对接，暂时放到/plugins/io_collector/目录下。
=> Collect I/O performance indicators in different configurations.

plugins/test_retransmit.py
【Jinrong Liang】
Add statistical indicators for the number of tcp retransmissions.
=> Add statistical indicators for the number of tcp retransmissions

plugins/db_modules.py, plugins/db_writer/bufferImpl.py, plugins/db_writer/db_writer_utils.py, plugins/db_writer/writerImpl.py
【谢李奥】
说明：
write2db01是方案一的实现；
write2db02是方案二的实现；
使用：
如果你认为你的插件涉及到调用write syscall interface，那么请调用db_module/write2db02
测试：
本地测试通过
=> db_writer 实现

Makefile, pkg/controllers/handler.go, static/index.html
感觉LMP里面能加日志的地方已经都加了，基本所有的error都有日志处理
=> about add  log

.github/workflows/ci.yml
=> Fixed CI error

eBPF_Visualization/eBPF_server/README.md, eBPF_Visualization/eBPF_server/在LMP项目后端中创建接口.md
1、Update Readme.md
2、Create a file:如何在lmp项目的后端添加一个接口.md
=> Reademeupdate(eBPF_server)

.github/workflows/ci.yml, eBPF_Supermarket/sidecar/bpf/README.md, eBPF_Supermarket/sidecar/bpf/common.go, eBPF_Supermarket/sidecar/bpf/probe/hook.go, eBPF_Supermarket/sidecar/bpf/probe/hook_test.go, eBPF_Supermarket/sidecar/bpf/tcpaccept/tcpaccept.go, eBPF_Supermarket/sidecar/bpf/tcpconnect/tcpconnect.go, eBPF_Supermarket/sidecar/bpf/tools.go, eBPF_Supermarket/sidecar/main.go, eBPF_Supermarket/sidecar/tools/net.go
To avoid git conflict, the CI problem is fixed by #277, not here.
=> [sidecar] add TCP accept and connect tracing logic

eBPF_Visualization/eBPF_server/service/ebpfplugins/ebpfplugins.go, eBPF_Visualization/eBPF_server/service/ebpfplugins/plugins.go
利用channel实现runSinglePlugin函数中error的接收以及对plugin的插件运行情况进行判断，当前LoadEbpfPlugins方法已经完全满足预期要达到的目标了。
=> Web backend]loadplugin update

eBPF_Supermarket/cilium_ebpf_probe/README.md, eBPF_Supermarket/cilium_ebpf_probe/cluster_utils/utils.go, eBPF_Supermarket/cilium_ebpf_probe/go.mod, eBPF_Supermarket/cilium_ebpf_probe/go.sum, eBPF_Supermarket/cilium_ebpf_probe/grpc_client/main.go, eBPF_Supermarket/cilium_ebpf_probe/grpc_server/main.go, eBPF_Supermarket/cilium_ebpf_probe/http2_tracing/bpf_program.go, eBPF_Supermarket/cilium_ebpf_probe/http2_tracing/http2_trace_uprobe.go, eBPF_Supermarket/cilium_ebpf_probe/http_client/main.go, eBPF_Supermarket/cilium_ebpf_probe/http_kprobe/main.go, eBPF_Supermarket/cilium_ebpf_probe/main.go
1.完善README部署可视化部件步骤
2.新增按照Pod内特定镜像容器的有选择添加探针
3.新增grpc协议streamID、endStream、Weight指标获取
4.新增将协议解析内容输出至xlsx功能
5.优化grpc event架构，以streamid作为event标识符
=> cilium_ebpf_probe

.github/workflows/go.yml, eBPF_Supermarket/cilium_ebpf_probe/k8s_yaml/g_server_pod.yaml, eBPF_Supermarket/cilium_ebpf_probe/k8s_yaml/http_server_pod.yaml
Completed the ci file, tested the dependencies
=> [cilium_ebpf_probe]ci

.github/workflows/ebpf_ddos.yml, .github/workflows/ebpf_lsm.yml, .github/workflows/ebpf_xdp.yml, .github/workflows/monitor_pod.yml, .github/workflows/monitor_sidecar.yml, .github/workflows/system_cpu.yml, .github/workflows/system_filesystem.yml, .github/workflows/system_memory.yml, .github/workflows/system_network.yml, .github/workflows/web_lmp.yml
由于 #349 中出现了一些触发条件的异常，因此提交一个PR进行整理。
其中，仅修改了 CI 文件的名称，和触发条件（`on` 字段）的内容。
整理后，将会同时监控 CI 文件和对应子目录的变更。
=>  Unify CI format and trigger conditions

eBPF_Documentation/readme.md
The link in this file links to the wrong address, so fix it.
=> modify the wrong link in readme.md
